name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.14.5
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.21.4
